CREATE VIEW VIEW_TAG_INFORMATION AS SELECT * FROM TAGS;
CREATE VIEW VIEW_ARE_FRIENDS AS SELECT * FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS SELECT ALBUMS.*,
PHOTOS.PHOTO_ID, PHOTOS.PHOTO_CAPTION, PHOTOS.PHOTO_CREATED_TIME,
PHOTOS.PHOTO_MODIFIED_TIME, PHOTOS.PHOTO_LINK
FROM ALBUMS
JOIN PHOTOS ON ALBUMS.ALBUM_ID = PHOTOS.ALBUM_ID;